### ISSUE TITLE
ERROR: No matching distribution found for vpype[all]>=1.10 

### ISSUE THREAD

**Issue by willyk26** [abey79/vpype-explorations#2]
Ive tried many things to resolve this error but can't seem to get around it.
Ive done a fresh install of vpype using pipx install "vpype[all]"
and am trying to install and inject this pluggin with pipx aswell

Ive also tried stand-alone installation with no avail
I'm using vpype version 1.90
and im running python 3.79 on Windows
vpype is running fine

**Comment by abey79** [comment]
Can you provide the full error log?

**Comment by willyk26** [comment]
PIP STDOUT
----------
Collecting git+https://github.com/abey79/vpype-explorations
  Cloning https://github.com/abey79/vpype-explorations to c:\users\willard\appdata\local\temp\pip-req-build-bhx3_jjp
  Resolved https://github.com/abey79/vpype-explorations to commit 49bc7f9b709a8cdbbfa6bcadafb3ccca9e22c0c5
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting axi@ git+https://github.com/fogleman/axi
  Cloning https://github.com/fogleman/axi to c:\users\willard\appdata\local\temp\pip-install-muxvz0ff\axi_0cc73b8468044ae59d353c874698c2af
  Resolved https://github.com/fogleman/axi to commit a5a12f01633076232be84a4e3321c80c7b9656b5
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: scipy in c:\users\willard\.local\pipx\venvs\vpype\lib\site-packages (from vpype-explorations==0.1.0) (1.7.3)
Requirement already satisfied: numpy in c:\users\willard\.local\pipx\venvs\vpype\lib\site-packages (from vpype-explorations==0.1.0) (1.21.6)
Requirement already satisfied: shapely in c:\users\willard\.local\pipx\venvs\vpype\lib\site-packages (from vpype-explorations==0.1.0) (1.8.0)
Collecting scikit-image
  Using cached scikit_image-0.19.2-cp37-cp37m-win_amd64.whl (12.5 MB)

PIP STDERR
----------
  Running command git clone --filter=blob:none --quiet https://github.com/abey79/vpype-explorations 'C:\Users\Willard\AppData\Local\Temp\pip-req-build-bhx3_jjp'
  Running command git clone --filter=blob:none --quiet https://github.com/fogleman/axi 'C:\Users\Willard\AppData\Local\Temp\pip-install-muxvz0ff\axi_0cc73b8468044ae59d353c874698c2af'
ERROR: Could not find a version that satisfies the requirement vpype[all]>=1.10 (from vpype-explorations) (from versions: 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.4.0, 1.5.0, 1.5.1, 1.6.0, 1.7.0, 1.8.0, 1.8.1, 1.9.0)
ERROR: No matching distribution found for vpype[all]>=1.10

**Comment by abey79** [comment]
Oh, you have Python 3.7. *vpype* requires 3.8 minimum as of 1.10, and my plugins (including this one) require *vpype* 1.10. I suggest you install a more recent version of Python (3.10 recommended), make sure `pipx` works with that newer version of Python, and then the installation should work.
